### ISSUE TITLE
Can't found the tviewer.h

### ISSUE THREAD

**Issue by zhanghm1995** [taketwo/tviewer#1]
Hi,
it's so kind of you to share this visualization project. When I use this library in my project, I get the error:
```
fatal error: tviewer/tviewer.h: no such file or folder
```
I just include this header in my cpp, and all other contents in `CMakeLists.txt` is same with yours. I don't know why, and maybe the `${TVIEWER_INCLUDE_DIRS}` is not valid? 

I also confused the `${TVIEWER_INCLUDE_DIRS}` is not defined in your `tviewer` CMakeLists file, or maybe I am not familiar the CMake syntax.

**Comment by taketwo** [comment]
I haven't used this code for a while now, but it used to work. What's the content of `${TVIEWER_INCLUDE_DIRS}` variable? You can print it with the following command in your CMakeLists:

```cmake
message(STATUS "TViewer include directories: ${TVIEWER_INCLUDE_DIRS}")
```

**Comment by zhanghm1995** [comment]
I use the code
```
message(STATUS "TViewer include directories: ${TVIEWER_INCLUDE_DIRS}")
```
it print nothing, do you know what might be the reason?
The TViewer can compile all ok by itself, but cannot compile in my project.

**Comment by taketwo** [comment]
I had a closer look and apparently the instructions are outdated. This variable is indeed not defined. The correct way to use the project now is:

```cmake
add_subdirectory(${CMAKE_SOURCE_DIR}/tviewer)
target_link_libraries(YOUR_EXE tviewer)
```

So you only need to 1) include TViewer CMake scripts 2) link your targets against a target created by TViewer.

**Comment by zhanghm1995** [comment]
Thanks for your reply！
It's may still not ok in my project, it's appreciate if you have time to update this project and give some examples how to use this. 
I also want to study how to write the CMakeLists file to package a project for others project to use, like
```cmake
find_package(my_created_lib REQUIRED)
include_directories(${MY_CREATED_LIB_INCLUDE_DIRS})
...
target_link_libraries(others_pro ${MY_CREATED_LIB_LIBRARIES}
```
It's always a black box for me that how to package my project using cmake like `OpenCV` or 'PCL'. Could you offer me some ideas or references?
Thanks a lot!

**Comment by taketwo** [comment]
To be honest, I don't plan on supporting this project. I used it myself last summer and it worked, but beyond that I don't plan any updates.

As for packaging, you may look at [this project](https://github.com/ethz-asl/libnabo). It's relatively small, but does perform all the needed export/install steps in CMake.

**Comment by zhanghm1995** [comment]
Ok, Thanks a lot!
